// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";

/// @title FeeManager
/// @notice Central registry of fee tiers so the Escrow and any future modules
///         (RFQ desk, referral program) read fee configuration from one place.
contract FeeManager is Ownable {
    struct FeeTier {
        uint256 minVolume; // cumulative trader volume (in USD-equivalent, 18 decimals) to qualify
        uint256 feeBps; // fee in basis points at this tier
    }

    FeeTier[] public tiers;
    mapping(address => uint256) public traderVolume; // running lifetime volume per trader
    mapping(address => address) public referrerOf; // trader => referrer
    uint256 public referralShareBps = 2000; // referrer gets 20% of the fee generated by their referee

    event TierUpdated(uint256 index, uint256 minVolume, uint256 feeBps);
    event VolumeRecorded(address indexed trader, uint256 amount, uint256 newTotal);
    event ReferralSet(address indexed trader, address indexed referrer);

    constructor(address initialOwner) Ownable(initialOwner) {
        // Default tiers: retail -> VIP
        tiers.push(FeeTier({ minVolume: 0, feeBps: 50 })); // 0.50%
        tiers.push(FeeTier({ minVolume: 100_000 ether, feeBps: 35 })); // 0.35%
        tiers.push(FeeTier({ minVolume: 1_000_000 ether, feeBps: 20 })); // 0.20%
    }

    function setTier(uint256 index, uint256 minVolume, uint256 feeBps) external onlyOwner {
        require(feeBps <= 1000, "FeeManager: fee too high");
        if (index == tiers.length) {
            tiers.push(FeeTier({ minVolume: minVolume, feeBps: feeBps }));
        } else {
            require(index < tiers.length, "FeeManager: bad index");
            tiers[index] = FeeTier({ minVolume: minVolume, feeBps: feeBps });
        }
        emit TierUpdated(index, minVolume, feeBps);
    }

    function setReferrer(address trader, address referrer) external {
        require(msg.sender == trader, "FeeManager: only self");
        require(referrerOf[trader] == address(0), "FeeManager: referrer already set");
        require(referrer != trader, "FeeManager: cannot refer self");
        referrerOf[trader] = referrer;
        emit ReferralSet(trader, referrer);
    }

    /// @notice Called by the backend/oracle (or the Escrow contract, if granted access)
    ///         after a trade settles, to update the trader's volume tier.
    function recordVolume(address trader, uint256 usdAmount) external onlyOwner {
        traderVolume[trader] += usdAmount;
        emit VolumeRecorded(trader, usdAmount, traderVolume[trader]);
    }

    function feeBpsFor(address trader) external view returns (uint256) {
        uint256 volume = traderVolume[trader];
        uint256 applicable = tiers[0].feeBps;
        for (uint256 i = 0; i < tiers.length; i++) {
            if (volume >= tiers[i].minVolume) {
                applicable = tiers[i].feeBps;
            }
        }
        return applicable;
    }

    function tierCount() external view returns (uint256) {
        return tiers.length;
    }
}
